- name: install monit
  apt: pkg=monit state=installed update_cache=true

- name: copy monitrc template (default on this command is to replace if remote is different than source)
  template: src=monitrc.j2 dest=/etc/monit/monitrc owner=root mode=0700

- name: copy mattermost alert to /usr/local/bin
  copy: src=files/mm-notify.py dest=/usr/local/bin/mm-notify.py owner=root mode=0700

- name: monit reload
  command: monit reload

- name: install pip for python 3 in ubuntu 16.04
  apt: pkg=python3-setuptools state=installed update_cache=true cache_valid_time=3600

- name: run install for pip
  command: easy_install3 pip

- name: install twilio
  pip: name=twilio

- name: copy monitrc template (default on this command is to replace if remote is different than source)
  template: src=twilio-alert.py.j2 dest=/usr/local/bin/twilio-alert.py owner=root mode=0600
